### ISSUE TITLE
Add website to the repo header

### ISSUE THREAD

**Issue by Syknapse** [BycorSanchez/resources#1]
Finding the live website, especially on mobile, is much easier if you include its link in the field designed for it in the repo deader.
Click `Edit` in the description
![image](https://user-images.githubusercontent.com/29199184/34556857-625f996e-f138-11e7-97dd-bb94f16fadee.png)
It reveals the option to add the link to the project **website**
![image](https://user-images.githubusercontent.com/29199184/34556881-78f4c41a-f138-11e7-95db-e58eecde0fca.png)

**Comment by BycorSanchez** [comment]
You're right, I have just included it. Thanks for your suggestion.
