### ISSUE TITLE
Collecting all the Udacity courses

### ISSUE THREAD

**Issue by dJani97** [BycorSanchez/resources#4]
Hi guys!
Can we add a list of courses that are included in the full FEWD path?
It would be very useful for everyone who dropped out but want to continue.

The courses are listed here: https://eu.udacity.com/course/front-end-web-developer-nanodegree--nd001

**Comment by BycorSanchez** [comment]
Hi!
Thanks for your suggestion. I'm currently adding generic type of resources (for example, Udacity as a whole) not individual courses, otherwise the list would be endless.
Anyway, I'll consider it for a future upgrade.
